version: '3'

services:
  thirtystf-db:
    image: postgres
    container_name: thirtystf-db
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    networks:
      - thirtystf
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - 54320:5432
  thirtystf:
    build:
      context: .
      dockerfile: Dockerfile
    image: thirtystf-backend/thirtystf
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: thirtystf
    tty: true
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_HOST=thirtystf-db
      - ANALYTIC_DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@thirtystf-db:5432/${DATABASE_NAME}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - thirtystf

networks:
  thirtystf:
    driver: bridge
    external: true

volumes:
  dbdata:
  node_modules:
